### ISSUE TITLE
NoMethodError - undefined method `clear' for nil:NilClass

### ISSUE THREAD

**Issue by emwalker** [Shopify/graphql-batch#70] opened 2017-11-13 22:05 UTC
I'm seeing this stack trace when I use graphql (`1.7.5`) and graphql-batch (`0.3.8`) together with subscriptions:
```
NoMethodError - undefined method `clear' for nil:NilClass:
  graphql-batch (0.3.8) lib/graphql/batch/setup.rb:22:in `ensure in block (2 levels) in
  graphql-batch (0.3.8) lib/graphql/batch/setup.rb:22:in `block (2 levels) in
  graphql (1.7.5) lib/graphql/relay/mutation/resolve.rb:18:in `call'
  graphql (1.7.5) lib/graphql/field.rb:230:in `resolve'
  graphql (1.7.5) lib/graphql/execution/execute.rb:254:in `call'
  graphql (1.7.5) lib/graphql/schema/middleware_chain.rb:45:in `invoke_core'
  graphql (1.7.5) lib/graphql/schema/middleware_chain.rb:38:in `invoke'
  graphql (1.7.5) lib/graphql/execution/execute.rb:108:in `resolve_field'
  graphql (1.7.5) lib/graphql/execution/execute.rb:72:in `block (2 levels) in
  graphql (1.7.5) lib/graphql/tracing.rb:56:in `block in trace'
  graphql (1.7.5) lib/graphql/tracing.rb:70:in `call_tracers'
  graphql (1.7.5) lib/graphql/tracing.rb:56:in `trace'
  graphql (1.7.5) lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
  graphql (1.7.5) lib/graphql/execution/execute.rb:64:in `resolve_selection'
  graphql (1.7.5) lib/graphql/execution/execute.rb:36:in `block in resolve_root_selection'
  graphql (1.7.5) lib/graphql/tracing.rb:56:in `block in trace'
  graphql (1.7.5) lib/graphql/tracing.rb:70:in `call_tracers'
  graphql (1.7.5) lib/graphql/tracing.rb:56:in `trace'
  graphql (1.7.5) lib/graphql/execution/execute.rb:32:in `resolve_root_selection'
  graphql (1.7.5) lib/graphql/execution/multiplex.rb:108:in `begin_query'
  graphql (1.7.5) lib/graphql/execution/multiplex.rb:81:in `block in run_as_multiplex'
  graphql (1.7.5) lib/graphql/execution/multiplex.rb:80:in `run_as_multiplex'
  graphql (1.7.5) lib/graphql/execution/multiplex.rb:69:in `block (2 levels) in run_queries'
  graphql (1.7.5) lib/graphql/execution/multiplex.rb:185:in `with_instrumentation'
  graphql (1.7.5) lib/graphql/execution/multiplex.rb:68:in `block in run_queries'
  graphql (1.7.5) lib/graphql/tracing.rb:56:in `block in trace'
  graphql (1.7.5) lib/graphql/tracing.rb:70:in `call_tracers'
  graphql (1.7.5) lib/graphql/tracing.rb:56:in `trace'
  graphql (1.7.5) lib/graphql/execution/multiplex.rb:58:in `run_queries'
  graphql (1.7.5) lib/graphql/execution/multiplex.rb:48:in `run_all'
  graphql (1.7.5) lib/graphql/schema.rb:299:in `block in multiplex'
  graphql (1.7.5) lib/graphql/schema.rb:606:in `with_definition_error_check'
  graphql (1.7.5) lib/graphql/schema.rb:298:in `multiplex'
  graphql (1.7.5) lib/graphql/schema.rb:275:in `execute'
  app/controllers/graphql_controller.rb:3:in `execute'
  actionpack (4.2.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
```

Any pointers on what's going on here and where to start for a potential fix?

**Comment by rmosolgo** [comment] 2017-11-13 22:11
Weird, here are a few proper links to some of those lines: 

https://github.com/Shopify/graphql-batch/blob/v0.3.8/lib/graphql/batch/setup.rb#L22
https://github.com/rmosolgo/graphql-ruby/blob/v1.7.5/lib/graphql/relay/mutation/resolve.rb#L18

It looks like this error is raised while executing a mutation, is that correct? 

In any case, could you share a GraphQL query that replicates the error?

**Comment by emwalker** [comment] 2017-11-13 22:37
> It looks like this error is raised while executing a mutation, is that correct?

Yes, a mutation is being issued.

> could you share a GraphQL query that replicates the error?

Here is the mutation that triggered the error:

```
{
  "query": "mutation AddProposalChangeMutation(\n  $input: AddProposalChangeInput!\n) {\n  addProposalChange(input: $input) {\n    changeEdge {\n      node {\n        id\n        databaseId\n        ...CreateRoleEditor_change\n      }\n    }\n  }\n}\n\nfragment CreateRoleEditor_change on Change {\n  id\n  databaseId\n  command\n}\n",
  "variables": {
    "input": {
      "proposalId": "djGFqquHWZJt_8M8F23dY_r6JzAfYkEyNEN129BEToMJVzzpcKAzeJ54eDe3KYwi",
      "command": {
        "type": "CreateRole",
        "requestedRole": {
          "name": "",
          "purpose": ""
        },
        "currentRole": {
          
        }
      }
    }
  }
}
```

**Comment by emwalker** [comment] 2017-11-13 23:08
There is a `GraphQL::Batch::NestedError` that would normally percolate beyond the `ensure` in the resolve proc, but for the `NoMethodError` exception that is being raised there.

**Comment by dylanahsmith** [comment] 2017-11-13 23:51
Given that the exception didn't happen just before the [begin-ensure block](https://github.com/Shopify/graphql-batch/blob/v0.3.8/lib/graphql/batch/setup.rb#L18), it looks like `GraphQL::Batch::Executor.current = nil` must have somehow happened inside the mutations fields resolve proc or in some other instrumentation wrapping the field resolve proc.

Does this exception only happen in that one mutation?  Can you reproduce the problem without the application logic of that mutation?  Is there any other field instrumentation for that field?

**Comment by emwalker** [comment] 2017-11-14 00:13
> Given that the exception didn't happen just before the begin-ensure block, it looks like GraphQL::Batch::Executor.current = nil must have somehow happened inside the mutations fields resolve proc or in some other instrumentation wrapping the field resolve proc.

Yes, that makes sense.

Here is more of the stack trace from an irb session.  I think what is happening is that the subscription code is triggering a query while the mutation is in flight:
```
NoMethodError: undefined method `bactracke' for #<GraphQL::Batch::NestedError: edError>
from (pry):8:in `rescue in call'
[8] pry(#<Glassfrog::Proposals::AddProposalChangeResolver>)> e.backtrace
=> ["/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-batch-0.3.8/lib/rb:5:in `star

 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-batch-0.3.8/lib/graphqlex.rb:9:i
,
 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/rb:172:in `blo
ation'",
 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/rb:172:in `eac

 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/rb:172:in `wit

 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/rb:68:in `bloc

 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/ock in trace'"

 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/ll_tracers'",
 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/ace'",
 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/rb:58:in `run_

 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/rb:48:in `run_

 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/ock in multipl

 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/th_definition_

 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/ltiplex'",
 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/ecute'",
 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/in `execute'",
 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/in `block in e

 "/Users/walker/code/h1/glassfrog/app/graph/glassfrog/subscriptions.rb:22:in `each'",
 "/Users/walker/code/h1/glassfrog/app/graph/glassfrog/subscriptions.rb:22:in d'",
 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/in `execute_al

 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-1.7.5/lib/graphql/in `trigger'",
 "/Users/walker/code/h1/glassfrog/app/services/proposal_service.rb:49:in '",
 "/Users/walker/code/h1/glassfrog/app/graph/glassfrog/proposals/add_proposal_change.rb:23:in
 "/Users/walker/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/graphql-batch-0.3.8/lib/graphql/batch/setup.rb:20:in `block
```

> Does this exception only happen in that one mutation? Can you reproduce the problem without the application logic of that mutation? Is there any other field instrumentation for that field?

If I remove code that eventually calls `Schema::subscriptions.trigger`, the `NestedError` is not encountered.

**Comment by rmosolgo** [comment] 2017-11-14 01:01
Oh wow, I'm guessing the subscription is not inside a background job, so `.trigger` is kicking off _more_ GraphQL execution, inside the the current one. 

So maybe one of those "inner" executions nullifies the current `executor`s, then it's nil by the time the mutation finishes.

**Comment by emwalker** [comment] 2017-11-14 01:03
That sounds right.  Is the contract that the `.trigger` must occur within a background job?

**Comment by rmosolgo** [comment] 2017-11-14 01:11
It always _seemed_ like the right thing to do, but I haven't quite mustered the energy to work out a consistent ActiveJob story with it. But given this interaction with GraphQL-batch, it _does_ seem more important! 

Are you able to give it a try in this case? Instead of calling `.trigger` during the mutation, enqueue a job that will call trigger separately. If it solves the problem here, I'm happy to add it to the graphql-ruby docs!

**Comment by emwalker** [comment] 2017-11-14 02:07
> Are you able to give it a try in this case? Instead of calling .trigger during the mutation, enqueue a job that will call trigger separately.

When I use DJ asynchronously, this works.  When I test the loop in a development environment, DJ is synchronous and so the exception is triggered.  Perhaps an additional requirement could be that DJ users should turn off dev mode.  But that feels like a code smell.

I'm wondering whether a stack or some other mechanism can be used in place of `GraphQL::Batch::Executor.current`, in order to allow more than one query to be in flight in a single thread.

**Comment by emwalker** [comment] 2017-11-14 03:06
> Could that be what is happening?

Quite possibly.  I'm not sure what the exact sequence of calls is, but I get the impression that this line is being called in the course of calling `::Promise.sync(old_resolve_proc.call(obj, args, ctx))`:

https://github.com/Shopify/graphql-batch/blob/master/lib/graphql/batch/setup.rb#L10

**Comment by emwalker** [comment] 2017-11-14 19:04
Here is a patch that has `GraphQL::Batch::Executor.current` delegate to a stack.  This fixes the immediate problems for me, but I'm not sure whether it would cause other problems:

https://gist.github.com/emwalker/444f36ba88dc4ad4c11e2896df99ed44

If this looks like a good way to take things, I can submit a PR.

**Comment by dylanahsmith** [comment] 2017-11-14 19:11
Does it make sense to have a separate executor for the nested query?  Wouldn't it make more sense to batch loads across the outer and inner queries?

**Comment by emwalker** [comment] 2017-11-14 19:14
In my particular case, the inner query will have to finish executing (and be resolved) before the outer one.  Does that make a difference?

**Comment by dylanahsmith** [comment] 2017-11-14 19:23
Functionally it would provide the same result, since it just calls Promise.sync to resolve the promises for the inner query.  Sharing an executor means that it could load data from the outer query while executing the inner query and avoids loading the same key for a loader twice since the loaders cache the result of loads already performed.

**Comment by emwalker** [comment] 2017-11-16 20:29
That makes sense. What about something like this, then?

https://gist.github.com/emwalker/8ea306492e3594db97622b77a04cf77a

**Comment by emwalker** [comment] 2017-11-24 20:20
@dylanahsmith I'm curious on your thoughts on the approach here.  Do you agree that it makes sense to get rid of the nested query error, in light of the fact that a subscription could trigger a nested query in a dev environment?

**Comment by dylanahsmith** [comment] 2017-11-29 15:54
Yes, I think it makes sense to get rid of the nested query error.

Some feedback on your gist:
* setup/teardown class methods on the executor sound like they would actually setup and teardown the executor each time they are called.  Perhaps start_batch/end_batch would better indicate what they do.
* the nesting level could be stored on the executor to avoid adding another thread local variable
* there is no need for the `!` in the method, since there is no corresponding method without the `!`, nor can I think of what behaviour a non-`!` method would do in this case
* `test_nested_batch` should actually test the behaviour (e.g. an unperformed load preceding the nested batch should be batched with a load in the second nested level and a load after the nested batch should still work)

**Comment by emwalker** [comment] 2017-11-29 22:49
Sounds good.

Here is a PR where I've attempted to incorporate your comments:

https://github.com/Shopify/graphql-batch/pull/72

**Comment by dylanahsmith** [comment] 2018-01-09 19:24
I think this has been fixed by https://github.com/rmosolgo/graphql-ruby/pull/1100 and https://github.com/Shopify/graphql-batch/pull/72 now

**Closed by dylanahsmith** 2018-01-09 19:24 UTC
